project:
  type: website

website:
  title: "Seoyeon's Blog"
  
  page-footer:
    border: true
    
  navbar:
    left:
      - text: Lectures
        href: https://seoyeonc.github.io/md/
      - text: Lectures_fastai
        href: https://seoyeonc.github.io/chch/
      - text: Research_ing
        href: https://seoyeonc.github.io/blog/
      - text: Research_fastai
        href: https://seoyeonc.github.io/ms/
        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seoyeonc
        
  sidebar:
    style: "docked"
    search: true
    contents:
      - 1_essays.qmd
      - section: "**Studies**"
        contents:
          - 2_graph.qmd
          - 2_ml.qmd
      - section: "**Researches**"
        contents:
          - 3_gode.qmd
          - 3_ittgnn.qmd
      
format:
  html:
    theme: 
        light: journal
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: false
    code-copy: false



