project:
  type: website
  output-dir: docs

website:
  title: "Seoyeon's Blog"
  
  page-footer:
    border: true
    
  navbar:
    left:
      - text: Lectures_ing
        href: https://seoyeonc.github.io/md/
      - text: Lectures_fastai
        href: https://seoyeonc.github.io/chch/
      - text: Research_ing
        href: https://seoyeonc.github.io/Research_area/
      - text: Research_fastai
        href: https://seoyeonc.github.io/ms/
      - text: GODE
        href: https://seoyeonc.github.io/GODE_blog/
      - text: HCAM
        href: https://seoyeonc.github.io/HCAM_blog/
      - text: ITTGNN
        href: https://seoyeonc.github.io/ITTGNN_blog/
      - text: Julia
        href: https://seoyeonc.github.io/julia/
        
        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seoyeonc
        
  sidebar:
    style: "docked"
    search: true
    contents:
      - 1_note.qmd
      - section: "**Studies**"
        contents:
          - 2_graph.qmd
          - 2_ept.qmd
          - 2_stgcn.qmd
          - 2_linearalgebra.qmd
      
format:
  html:
    theme: 
        light: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: false
    code-copy: false



